### ISSUE TITLE
Files heap DOM missing on update playlist page

### ISSUE THREAD

**Issue by Evgenijisaev** [rtv-group/planner#4] opened 2017-10-03 13:15 UTC
not a correct display of files heap. 
![46](https://user-images.githubusercontent.com/32486209/31126925-f2a8f5a0-a855-11e7-9098-a7140a98187f.jpg)

**Comment by AlexanderKosianchuk** [comment] 2017-10-03 21:26
Bug caused by asset manager implementation. 
Fixed by 39410af

**Closed as completed** 2017-10-03 21:26 UTC
Labels: bug
